const PublicIndex = () => {
  return <div>PublicIndex</div>;
};

export default PublicIndex;

/*
  MOSTRAR TODAS LAS RECETAS QUE AGERGÓ EL USUARIO
  MOSTRAR EN OTRO APARTADO LOS FAVORITOS
  LOS FAVORITOS SOLO SE MOSTRARA LA IMAGEN Y ABAJO EL NOMBRE
  AL DARLE CLICK SE IRÁ A LA PARTE PERSONAL DE LA PÁGINA
*/

//TODO: TERMINAR COMPONENTE
